version: '3.8'

services:
  app:
    build: .
    ports:
      - "10000:80"
    environment:
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=YOUR_DATABASE
      - DB_USERNAME=YOUR_USERNAME
      - DB_PASSWORD=YOUR_PASSWORD
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_ROOT_PASSWORD
      MYSQL_DATABASE: YOUR_DATABASE
      MYSQL_USER: YOUR_USERNAME
      MYSQL_PASSWORD: YOUR_PASSWORD
    ports:
      - "3306:3306"
